version: '3'
services:
  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile.dev
    volumes:
    - /var/tmp/heaven_in_mouth_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: heaven_in_mouth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  flask:
    build:
      context: flask_app
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    volumes:
      - ./flask_app:/app
  front:
    build:
      context: front
      dockerfile: Dockerfile.dev
    profiles: ["front"]
    ports:
      - "4321:4321"
    volumes:
      - ./front/src:/app/src

