version: '3'
services:
  postgres:
    container_name: postgres_test
    build:
      context: postgres
      dockerfile: Dockerfile.test
    environment:
      POSTGRES_DB: heaven_in_mouth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  flask:
    container_name: flask_test
    build:
      context: .
      dockerfile: flask_app/Dockerfile.test
    depends_on:
      - postgres

