version: '3'
services:
  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile.dev
    volumes:
    - /var/tmp/heaven_in_mouth_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: heaven_in_mouth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  flask:
    build:
      context: flask_app
      dockerfile: Dockerfile.dev
    # Please do note that if port 5000 is already in use, you can change the port to any other port or kill the process using the port
    # sudo lsof -i:5000 , you take process PID and run:  kill -9 <PID> , killing is the better option than cahnging the port source code
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    volumes:
      - ./flask_app:/app
  front:
    build:
      context: front
      dockerfile: Dockerfile.dev
    ports:
      - "4321:4321"
    # Volumes shoud be working but don't know why they aren't 
    # Implement volumes for front in docker compose TODO
    volumes:
      - ./front/src:/app/src

