FROM python:3.9.19-alpine
WORKDIR /app
COPY ./requirements.txt ./

ENV FLASK_APP=app.py
ENV FLASK_ENV=development

RUN pip install -r requirements.txt
COPY . .
CMD ["flask", "run", "--host=0.0.0.0"]
EXPOSE 5000
