FROM postgres:16.3-alpine
WORKDIR /var/lib/psql/data

ENV POSTGRES_USER=postgres
# When the project is bigger replce the password with a secret
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=heaven_in_mouth

# There is a problem with direcotires -> Figure out how workidir works
COPY ./db_setup.sql ./db_setup.sh ./
ENTRYPOINT "&& ./db_setup.sh"
