name: Create Jira Issue on GitHub Issue Creation

on: [push]

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Jira Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Extract Priority from Issue Name
        id: extract_priority
        run: |
          priority_regex="(Lowest|Low|Medium|High|Highest)"
          issue_name="(Lowest) Test issue"
          if [[ $issue_name =~ $priority_regex ]]; then
            echo "priority=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "priority=Medium" >> $GITHUB_OUTPUT
          fi

      - name: Jira Create issue
        uses: atlassian/gajira-create@v3
        with:
          project: "KAN"
          summary: "(Lowest) Test issue"
          description: "Test issue for jira actions"
          issuetype: "Task"
          priority: "${{ steps.extract_priority.outputs.priority }}"
